version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: www-data
                uid: 1000
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel
    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel
    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/mysql/lib:/var/lib/mysql
#            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password
        restart: always
        ports:
            - 8081:80
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
